In [1]:
from tensorflow.keras.preprocessing import image
import numpy as np


In [2]:
img = image.load_img('10002.jpg', target_size=(224, 224))


In [3]:
img_array = image.img_to_array(img)

In [4]:
print(img_array.shape)

(224, 224, 3)


In [5]:
expanded_img_array = np.expand_dims(img_array, axis=0)

In [6]:
print(expanded_img_array.shape)

(1, 224, 224, 3)


In [7]:
expanded_img_array

array([[[[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        ...,

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
       

In [8]:
from tensorflow.keras.applications.resnet50 import ResNet50, preprocess_input
import tensorflow
from tensorflow.keras.preprocessing import image
from tensorflow.keras.layers import GlobalMaxPooling2D
import numpy as np

In [9]:
model = ResNet50(
    weights='imagenet',
    include_top=False,
    input_shape=(224, 224, 3)
)

# Freeze model
model.trainable = False

# Add pooling layer
model = tensorflow.keras.Sequential([
    model,
    GlobalMaxPooling2D()
])

94765736/94765736 ━━━━━━━━━━━━━━━━━━━━ 5s 0us/step


In [10]:
preprocessed_img = preprocess_input(expanded_img_array)

print(preprocessed_img.shape)



(1, 224, 224, 3)


In [11]:
preprocessed_img

array([[[[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ]],

        [[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ]],

        [[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ]],

        ...,

        [[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,


In [17]:
model.predict(preprocessed_img).shape

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step


(1, 2048)

In [13]:
model.predict(preprocessed_img).flatten()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 241ms/step


array([ 0.       , 10.38125  ,  2.0249777, ...,  0.4012525,  0.       ,
       15.491596 ], dtype=float32)

In [15]:
model.predict(preprocessed_img).flatten() / np.linalg.norm(model.predict(preprocessed_img).flatten())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step


array([0.        , 0.03642138, 0.00710439, ..., 0.00140775, 0.        ,
       0.05435042], dtype=float32)

In [18]:
np.sqrt(np.dot(model.predict(preprocessed_img).flatten(), model.predict(preprocessed_img).flatten()))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 310ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step


np.float32(285.03177)